CGWAP/src/cgwap/util/session/SessionBean.java
package cgwap.util.session;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

/**
 * SessionBean manages all methods to interact with the session. For every
 * logged in user it stores
 * only the userId in Session.
 */
@ManagedBean
@ViewScoped
public class SessionBean implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -2681990698041167482L;

    @ManagedProperty("#{facesBroker}")
    private FacesBroker facesBroker;

    /**
     * The key under which the users' id is stored in session to remember login
     * state.
     */
    public final static String SESSION_USER_KEY = "current-user";

    // -------------------------------------------------------------------------
    // Getter / Setter
    // -------------------------------------------------------------------------

    /**
     * @return FacesBroker for UnitTesting
     */
    public FacesBroker getBroker() {
        return this.facesBroker;
    }

    /**
     * @param facesBroker
     *            - FacesBroker for UnitTesting
     */
    public void setFacesBroker(FacesBroker facesBroker) {
        this.facesBroker = facesBroker;
    }

    // -------------------------------------------------------------------------
    // Methods
    // -------------------------------------------------------------------------
    /**
     * Adds a levelUp message to be displayed to the user.
     * 
     * @param error
     *            - error message to declare in faces context
     */
    public void setLevelUp(String level) {
        FacesContext facesContext = facesBroker.getFacesContext();
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, level, null));
    }

    /**
     * Adds an error message to be displayed to the user.
     * 
     * @param error
     *            - error message to declare in faces context
     */
    public void setError(String error) {
        FacesContext facesContext = facesBroker.getFacesContext();
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, error, null));
    }

    /**
     * Adds an info message to be displayed to the user.
     * 
     * @param info
     *            - info message to declare in faces context
     */
    public void setInfo(String info) {
        FacesContext facesContext = facesBroker.getFacesContext();
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, info, null));
    }

    /**
     * Check if error messages are present to present.
     * 
     * @return true, if error messages are present
     */
    public boolean isHasErrorMessage() {
        FacesContext context = facesBroker.getFacesContext();
        return !context.getMessageList().isEmpty()
                &&
                context.getMaximumSeverity().equals(FacesMessage.SEVERITY_ERROR);
    }

    /**
     * Check if levelUp messages are present to present.
     * 
     * @return true, if messages are present
     */
    public boolean isHasLevelMessage() {
        FacesContext context = facesBroker.getFacesContext();
        return !context.getMessageList().isEmpty()
                &&
                context.getMaximumSeverity().equals(FacesMessage.SEVERITY_WARN);
    }

    /**
     * Check if info messages are present to present.
     * 
     * @return true, if info messages are present
     */
    public boolean isHasInfoMessage() {
        FacesContext context = facesBroker.getFacesContext();
        return !context.getMessageList().isEmpty()
                &&
                context.getMaximumSeverity().equals(FacesMessage.SEVERITY_INFO);
    }

    /**
     * Reads the user id which is stored in the session.
     * 
     * @return userId, otherwise 0
     */
    public int getCurrentUserId() {
        Object sessionUser = this.getSessionAttribute(SessionBean.SESSION_USER_KEY);

        if (sessionUser != null && sessionUser instanceof Integer) {
            return (Integer) sessionUser;
        } else {
            return 0;
        }
    }

    /**
     * Sets the user id in the session, while creating a new session for that to
     * prevent session
     * fixation.
     * 
     * @param userId
     *            - the user id to store
     */
    public void setUserLoggedIn(int userId) {
        // prevent session fixation
        HttpSession session = this.getSession();
        synchronized (session) {
            session.invalidate();
        }

        this.setSessionAttribute(SessionBean.SESSION_USER_KEY, userId);
    }

    /**
     * Checks if a user-id is stored in the session.
     * 
     * @return true, if a user id is set
     */
    public boolean isLoggedIn() {
        Object sessionUser = this.getSessionAttribute(SessionBean.SESSION_USER_KEY);
        return sessionUser != null && sessionUser instanceof Integer;
    }

    /**
     * Removes the user id from session and invalidates the session to logout a
     * user.
     */
    public void logout() {
        HttpSession session = this.getSession();

        synchronized (session) {
            session.removeAttribute(SessionBean.SESSION_USER_KEY);
            session.invalidate();
        }
    }

    /**
     * Removes the user id from session the session to logout a user, but keeps
     * the other session
     * data.
     */
    public void logoutWithoutInvalidation() {
        HttpSession session = this.getSession();

        synchronized (session) {
            session.removeAttribute(SessionBean.SESSION_USER_KEY);
        }
    }

    // -------------------------------------------------------------------------
    // Helper
    // -------------------------------------------------------------------------
    /**
     * Uses the FacesBroker to return the faces context.
     * 
     * @return the current faces context
     */
    public FacesContext getFacesContext() {
        return facesBroker.getFacesContext();
    }

    /**
     * Get any value stored for a key in the session.
     * 
     * @param key
     *            - the key to search the value for
     * @return the found value, otherwise null
     */
    private Object getSessionAttribute(String key) {
        HttpSession session = this.getSession();
        Object attribute = null;

        synchronized (session) {
            attribute = session.getAttribute(key);
        }

        return attribute;
    }

    /**
     * Set any value named by a key in the session.
     * 
     * @param key
     *            - the key to save the value for
     * @param obj
     *            - the value
     */
    private void setSessionAttribute(String key, Object obj) {
        HttpSession session = this.getSession();

        synchronized (session) {
            session.setAttribute(key, obj);
        }
    }

    /**
     * Returns the session using the facesBroker.
     * 
     * @return the current session
     */
    private HttpSession getSession() {
        HttpSession session = (HttpSession) facesBroker.getFacesContext().getExternalContext().getSession(true);
        return session;
    }

}

CGWAP/WebContent/members/template/content.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets">
    
    <div class="jumbotron">
        <h1>Super awesome marketing speak!</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <a class="btn btn-large btn-success" href="#">Sign up today</a>
    </div>

    <hr/>

    <div class="row-fluid marketing">
        <div class="span6">
            <h4>Subheading</h4>
            <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

            <h4>Subheading</h4>
            <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

            <h4>Subheading</h4>
            <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="span6">
            <h4>Subheading</h4>
            <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

            <h4>Subheading</h4>
            <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

            <h4>Subheading</h4>
            <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
    </div>
 
</ui:composition>

CGWAP/WebContent/members/template/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<div id="footer">
		<div class="container">
			<p class="text-muted credit">
				<h:form>

					<h:link outcome="about">
						<span class="glyphicon glyphicon-align-justify"></span>   #{msg.about}</h:link>
					<!--                   * -->
					<!--                 <h:link outcome="help" value="#{msg.help}"/>  -->


				</h:form>
			</p>
		</div>
	</div>

</ui:composition>

CGWAP/WebContent/members/template/header.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<h:form>

		<div class="masthead">
			<h3 class="text-muted">CGWAP</h3>
			<h:panelGroup rendered="#{sessionBean.loggedIn}">
				<ul class="nav nav-justified">
					<li><h:link outcome="index">
							<span class="glyphicon glyphicon-home"></span>   #{msg.home}</h:link></li>
					<li><h:link outcome="asking">
							<span class="glyphicon glyphicon-question-sign"></span> #{msg.asking}</h:link></li>
					<li><h:link outcome="answering">
							<span class="glyphicon glyphicon-exclamation-sign"></span> #{msg.answering}</h:link></li>
					<li><h:link outcome="userProfile">
							<span class="glyphicon glyphicon-user"></span> #{msg.userProfile}</h:link></li>
					<li><h:commandLink outcome="logout" action="#{userAction.logout()}">
							<span class="glyphicon glyphicon-minus-sign"></span> #{msg.logout}</h:commandLink></li>
				</ul>
			</h:panelGroup>


			<h:panelGroup rendered="#{!sessionBean.loggedIn}">
				<ul class="nav nav-justified">
					<li><h:link outcome="index">
							<span class="glyphicon glyphicon-home"></span>   #{msg.home}</h:link></li>
					<li><h:link outcome="asking">
							<span class="glyphicon glyphicon-question-sign"></span> #{msg.asking}</h:link></li>
					<li><h:link outcome="answering">
							<span class="glyphicon glyphicon-exclamation-sign"></span> #{msg.answering}</h:link></li>
					<li><h:link outcome="login">
							<span class="glyphicon glyphicon-log-in"></span> #{msg.login}</h:link></li>
					<li><h:link outcome="register">
							<span class="glyphicon glyphicon-heart"></span> #{msg.signup}</h:link></li>
				</ul>
			</h:panelGroup>
		</div>


	</h:form>
	<!-- show only for global info messages -->
	<h:panelGroup layout="block" rendered="#{sessionBean.hasInfoMessage}" class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">x</button>
		<h:messages globalOnly="true" layout="list" />
	</h:panelGroup>

	<h:panelGroup layout="block" rendered="#{sessionBean.hasLevelMessage}" class="alert alert-info">
		<button type="button" class="close" data-dismiss="alert">x</button>
		<h4>#{msg.levelUpMessage}</h4>
		<h:messages globalOnly="true" layout="list" />
	</h:panelGroup>

	<h:panelGroup layout="block" rendered="#{sessionBean.hasErrorMessage}" class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">x</button>
		<h4>#{msg.sorry}</h4>
		<h:messages globalOnly="true" layout="list" />
	</h:panelGroup>

</ui:composition>

CGWAP/WebContent/members/template/layout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>

	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="CGWAP" />
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="#{request.contextPath}/bootstrap.css" />

    <!-- Bootstrap Justified CSS -->
    <link rel="stylesheet" type="text/css" href="#{request.contextPath}/justified-nav.css" />

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" type="text/css" href="#{request.contextPath}/font-awesome.css" />
    

	<title><ui:insert name="title">CGWAP</ui:insert></title>

</h:head>

<h:body>

	<div class="container">

		<ui:insert name="header">
			<ui:include src="header.xhtml" />
		</ui:insert>




		<ui:insert name="content">
			<ui:include src="content.xhtml" />
		</ui:insert>

	</div>

	<hr />


	<h:outputScript library="js" name="jquery.js" />
	<h:outputScript library="js" name="bootstrap.js" />
	<h:outputScript library="js" name="main.js" />
	<script type="text/javascript">
		$('.pop').popover({});
	</script>

	<ui:insert name="footer">
		<ui:include src="footer.xhtml" />
	</ui:insert>

	<ui:insert name="scripts">

	</ui:insert>

</h:body>
</html>